### ISSUE TITLE
Feature request: impl (`De`)`Serialize` for the float structs

### ISSUE THREAD

**Issue by Banyc** [RazrFalcon/strict-num#2]
# Background

There are scenarios where:
- users want to define normalized floating values in a config file to represent a proportion.
- users want to send a proportion via a HTTP request.
- ...

Using this library, they define those fields as `NormalizedF64` at the request struct or the config struct. However, currently this library didn't implement `serde` traits for the type.

# Why

By implementing `serde` traits, the problems above can be solved in a user-friendly way.

`serde` crate is extremely popular in the Rust ecosystem. As of writing this, `serde` ranks 9th at the "[Most Recent Downloads](https://crates.io/crates?sort=recent-downloads)" category. The non-zero types like `NonZeroUsize` is very similar to the idea of this crate by forcing invalid states to be unrepresentable. `serde` crate implements both `Serialize` and `Deserialize` for those types. This crate fills the similar need for floating numbers. For the coherent and similar user experience, it may be a good reason to also implement `serde` traits for those types.

# Implementations for the std Non-zero types

- `Serialize`: <https://docs.rs/serde/1.0.193/src/serde/ser/impls.rs.html#613-620>
- `Deserialize`: <https://docs.rs/serde/1.0.193/src/serde/de/impls.rs.html#367-372>

**Comment by RazrFalcon** [comment]
Sure, maybe one day.
